services:
  ircd:
    image: inspircd/inspircd-docker
    ports:
      - "6667:6667"

  zani:
    build: .
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    depends_on:
      - ircd
