.PHONY: help build run test deploy-dev deploy-prod clean docker-build docker-run

# Default target
help:
	@echo "Sexo IRC Bot - Available targets:"
	@echo ""
	@echo "Development:"
	@echo "  build        - Build the project with cargo"
	@echo "  run          - Run the bot locally"
	@echo "  test         - Run tests"
	@echo "  clean        - Clean build artifacts"
	@echo ""
	@echo "Container/Deployment:"
	@echo "  docker-build - Build Docker image"
	@echo "  docker-run   - Run with docker-compose"
	@echo "  deploy-dev   - Deploy to development environment"
	@echo "  deploy-prod  - Deploy to production environment"
	@echo ""
	@echo "Configuration:"
	@echo "  config-dev   - Generate development config"
	@echo "  config-prod  - Generate production config"

# Development targets
build:
	cargo build --release

run:
	cargo run

test:
	cargo test

clean:
	cargo clean
	rm -f data/sexo.db

# Docker targets
docker-build:
	docker build -t sexo:latest .

docker-run:
	docker-compose up --build

# Deployment targets
deploy-dev:
	./deploy.sh --dev

deploy-prod:
	./deploy.sh --prod

# Configuration targets
config-dev:
	@echo "Development configuration will be generated by Ansible"
	@echo "Edit group_vars/development.yml to customize"

config-prod:
	@echo "Production configuration will be generated by Ansible"
	@echo "Edit group_vars/production.yml to customize"
